// ESCAPE CALLの型・錠の生成・表示文言の定数（基本設計/13_ESCAPECALLゲームモジュール.md）
export {
  COLORS,
  COLOR_IDS,
  SHAPES,
  SHAPE_IDS,
  SYMBOL_IDS,
  colorOf,
  isSymbolId,
  shapeOf,
  symbolIdOf,
  symbolNameEn,
  symbolNameJa,
  type ColorId,
  type ShapeId,
  type SymbolId,
} from "./symbols";

export {
  RULE_IDS,
  RULE_TARGET,
  SKIPPED_SYMBOL_COUNT,
  SKIP_RULE_IDS,
  applyDigitRule,
  applySymbolRule,
  computeCode,
  isRuleId,
  isSkippedBy,
  type RuleId,
  type RuleSpec,
} from "./rules";

export {
  LOCK_COUNT,
  LOCK_SPECS,
  assignPieces,
  generateLock,
  generateLocks,
  kindsOf,
  rankByLevel,
  solveFromPieces,
  usedSymbolsOf,
  type GeneratedLock,
  type LockSpec,
  type MapEntry,
  type MapPiece,
  type OrderPiece,
  type Participant,
  type Piece,
  type PieceKind,
  type PiecePart,
  type RuleEntry,
  type RulePiece,
  type RuleTextOf,
} from "./lock";

export {
  COLOR_PLACEHOLDER,
  MIN_KEY_EXPRESSIONS,
  PACK_ID_PATTERN,
  SHAPE_PLACEHOLDER,
  countOccurrences,
  isSymbolRule,
  phraseTierFor,
  placeholderOf,
  ruleTextFor,
  ruleTextJa,
  type EscapeCallPack,
  type KeyExpression,
  type LockLabel,
  type RulePhrase,
  type SceneText,
} from "./pack";

export {
  ACTIONS,
  CODE_PATTERN,
  ERROR_CODES,
  ESCAPE_SECONDS,
  STAGES,
  STAGE_DEADLINE_SECONDS,
  STAGE_LABELS_JA,
  currentLockOf,
  hintCountOf,
  rankOf,
  type ActionName,
  type AttemptEntry,
  type ErrorCode,
  type EscapeCallPackSummary,
  type EscapeCallPublic,
  type EscapeCallResult,
  type EscapeCallSecret,
  type EscapeCallSettings,
  type HintEntry,
  type HintPayload,
  type HolderEntry,
  type LockPublic,
  type LockSolution,
  type Rank,
  type Stage,
  type SubmitPayload,
} from "./game";
