// お題データのスキーマ型（正本）とBLIND ROOMのランタイム型・表示文言の定数
export type { BlindRoomPack, ItemDefinition, ItemSet, KeyExpression, Tier } from "./pack";
export {
  HINT_BLANK,
  ICON_BASE_PATH,
  ITEM_ID_PATTERN,
  MAX_ITEM_ID_LENGTH,
  MAX_ITEM_WORDS,
  MIN_DESCRIBER_HINTS,
  MIN_ITEMS,
  MIN_KEY_EXPRESSIONS,
  countWords,
  hasHintBlank,
  iconUrl,
  isValidIconId,
  isValidItemId,
  tierFor,
} from "./pack";

export {
  BOARD_SIZES,
  BOARD_SIZE_IDS,
  DEFAULT_BOARD_SIZE_ID,
  boardSizeOf,
  cellCountOf,
  columnOrdinalsEn,
  isBoardSizeId,
  rowWordsEn,
  type BoardSize,
  type BoardSizeId,
} from "./board-size";

export {
  PLACE_COUNT,
  countMatches,
  emptyBoard,
  generateSample,
  hasDuplicateItem,
  isBoard,
  placedCount,
  placedItemIds,
  type Board,
} from "./board";

export {
  ACTIONS,
  BUILDING_SECONDS,
  DEFAULT_SETTINGS_BOARD_SIZE_ID,
  ERROR_CODES,
  STAGES,
  STAGE_DEADLINE_SECONDS,
  STAGE_LABELS_JA,
  describerPlayerIdOf,
  describerPointsOf,
  hintCountFor,
  isFinalRound,
  pointsOf,
  type ActionName,
  type BlindRoomPackSummary,
  type BlindRoomPublic,
  type BlindRoomResult,
  type BlindRoomSecret,
  type BlindRoomSettings,
  type BoardResult,
  type DescriberSecret,
  type DonePayload,
  type ErrorCode,
  type ListenerSecret,
  type PaletteItem,
  type PlacePayload,
  type RoundRecord,
  type ScoreEntry,
  type Stage,
} from "./game";
